if(CASE STREQUAL "valid")
    set(arguments check-config "${SOURCE_DIR}/server/config/development.conf")
elseif(CASE STREQUAL "version")
    set(arguments --version)
elseif(CASE STREQUAL "help")
    set(arguments --help)
elseif(CASE STREQUAL "no_arguments")
    set(arguments)
elseif(CASE STREQUAL "extra_argument")
    set(arguments --version unexpected)
elseif(CASE STREQUAL "unavailable")
    set(arguments check-config "${FIXTURE_DIR}/does-not-exist.conf")
elseif(CASE STREQUAL "directory")
    set(arguments check-config "${FIXTURE_DIR}")
else()
    set(arguments check-config "${FIXTURE_DIR}/${CASE}.conf")
endif()

execute_process(COMMAND "${CLI}" ${arguments}
    RESULT_VARIABLE exit_code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
if(NOT "${exit_code}" STREQUAL "${EXPECTED_EXIT}")
    message(FATAL_ERROR "Expected exit ${EXPECTED_EXIT}; got ${exit_code}. stderr=${stderr}")
endif()
if(EXPECTED_EXIT EQUAL 0)
    if(NOT stderr STREQUAL "")
        message(FATAL_ERROR "Successful validation unexpectedly wrote to stderr: ${stderr}")
    endif()
    set(payload "${stdout}")
else()
    if(NOT stdout STREQUAL "")
        message(FATAL_ERROR "Rejected input unexpectedly wrote to stdout: ${stdout}")
    endif()
    set(payload "${stderr}")
    string(JSON error_code GET "${payload}" code)
    if(NOT error_code STREQUAL EXPECTED_CODE)
        message(FATAL_ERROR "Expected error ${EXPECTED_CODE}; got ${error_code}")
    endif()
endif()

if(CASE STREQUAL "version")
    string(JSON component GET "${payload}" component)
    string(JSON version GET "${payload}" version)
    string(JSON phase GET "${payload}" phase)
    if(NOT component STREQUAL "draconic_foundation" OR NOT version STREQUAL EXPECTED_VERSION OR NOT phase EQUAL 0)
        message(FATAL_ERROR "Version output does not describe this foundation: ${payload}")
    endif()
    return()
endif()
if(CASE STREQUAL "help")
    if(NOT payload MATCHES "Offline foundation diagnostics only")
        message(FATAL_ERROR "Help must disclose the offline-only scope: ${payload}")
    endif()
    return()
endif()

string(JSON event GET "${payload}" event)
string(JSON services GET "${payload}" services_started)
if(NOT event STREQUAL EXPECTED_EVENT OR NOT services EQUAL 0)
    message(FATAL_ERROR "Diagnostic output incorrectly describes its result: ${payload}")
endif()
if(CASE STREQUAL "valid")
    string(JSON mode GET "${payload}" mode)
    string(JSON realm GET "${payload}" realm_id)
    string(JSON shard GET "${payload}" shard_id)
    if(NOT mode STREQUAL "offline_validation" OR NOT realm EQUAL 1 OR NOT shard EQUAL 1)
        message(FATAL_ERROR "Successful validation returned incorrect identity: ${payload}")
    endif()
endif()
if(payload MATCHES "never-echo-this")
    message(FATAL_ERROR "Configuration input leaked into diagnostics")
endif()
