# Also usable from builds configured with BUILD_TESTING=OFF.
foreach(required BUILD_DIR INSTALL_PREFIX INSTALL_BINDIR INSTALL_DATADIR EXPECTED_VERSION)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing required argument: ${required}")
    endif()
endforeach()

if(NOT IS_ABSOLUTE "${BUILD_DIR}" OR NOT IS_ABSOLUTE "${INSTALL_PREFIX}")
    message(FATAL_ERROR "Build and staging directories must be absolute paths")
endif()
file(REAL_PATH "${BUILD_DIR}" build_root)
file(REAL_PATH "${INSTALL_PREFIX}" staging_root)
cmake_path(IS_PREFIX build_root "${staging_root}" NORMALIZE inside_build)
if(NOT inside_build OR staging_root STREQUAL build_root)
    message(FATAL_ERROR "Smoke installation must use a staging subdirectory of BUILD_DIR")
endif()
foreach(directory INSTALL_BINDIR INSTALL_DATADIR)
    if(IS_ABSOLUTE "${${directory}}")
        message(FATAL_ERROR "Smoke installation requires relative install directories")
    endif()
endforeach()
if(NOT DEFINED EXECUTABLE_SUFFIX)
    set(EXECUTABLE_SUFFIX "")
endif()
file(REAL_PATH "${staging_root}/${INSTALL_BINDIR}/draconic_foundation${EXECUTABLE_SUFFIX}" cli)
file(REAL_PATH "${staging_root}/${INSTALL_DATADIR}/draconic-mmo/examples/development.conf" config_file)
foreach(artifact cli config_file)
    cmake_path(IS_PREFIX staging_root "${${artifact}}" NORMALIZE inside_staging)
    if(NOT inside_staging)
        message(FATAL_ERROR "Installed artifact path escapes the staging directory")
    endif()
endforeach()
# A failed or incomplete install must not succeed by running an artifact from an earlier test.
file(REMOVE "${cli}" "${config_file}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}"
    --prefix "${INSTALL_PREFIX}" --config "${CONFIG}"
    RESULT_VARIABLE install_result OUTPUT_VARIABLE install_output ERROR_VARIABLE install_error
    TIMEOUT 20)
if(NOT "${install_result}" STREQUAL "0")
    message(FATAL_ERROR "Install failed: ${install_result}\n${install_output}\n${install_error}")
endif()
if(NOT EXISTS "${cli}" OR NOT EXISTS "${config_file}")
    message(FATAL_ERROR "Install did not produce the executable and example configuration")
endif()

execute_process(COMMAND "${cli}" check-config "${config_file}"
    WORKING_DIRECTORY "${INSTALL_PREFIX}"
    RESULT_VARIABLE run_result OUTPUT_VARIABLE payload ERROR_VARIABLE run_error TIMEOUT 10)
if(NOT "${run_result}" STREQUAL "0" OR NOT run_error STREQUAL "")
    message(FATAL_ERROR "Installed executable failed: ${run_result}\n${run_error}")
endif()
string(JSON event GET "${payload}" event)
string(JSON mode GET "${payload}" mode)
string(JSON version GET "${payload}" version)
string(JSON services GET "${payload}" services_started)
if(NOT event STREQUAL "config_valid" OR NOT mode STREQUAL "offline_validation" OR
   NOT version STREQUAL EXPECTED_VERSION OR NOT services EQUAL 0)
    message(FATAL_ERROR "Installed executable returned an unexpected result: ${payload}")
endif()
message(STATUS "Installed offline executable and example configuration verified (${version})")
